export type RestaurantStatus = "open" | "closed" | "limited";

export type MenuSection = {
  title: string;
  items: string[];
};

export type RestaurantDetail = {
  slug: string;
  name: string;
  cuisine: string;
  area: string;
  rating: string;
  reviews: string;
  price: string;
  priceTier: string;
  hours: string;
  description: string;
  about: string;
  address: string;
  phone?: string;
  email?: string;
  website?: string;
  menuUrl?: string;
  menu: string[];
  menuSections: MenuSection[];
  status: RestaurantStatus;
  statusLabel: string;
  statusNote?: string;
  position: string;
};

const entries: Omit<RestaurantDetail, "slug">[] = [
  {
    name: "Veritas",
    cuisine: "Contemporary American",
    area: "Downtown",
    rating: "4.8",
    reviews: "1.4k",
    price: "$15-$115",
    priceTier: "$$$$",
    hours: "Tue-Sat, 5-10 pm",
    description: "A celebrated tasting-menu room where Ohio ingredients meet exacting, quietly theatrical cooking.",
    about:
      "Veritas is one of Columbus' signature special-occasion dining rooms, pairing an immersive themed tasting menu with a polished underground setting and a smaller bar program for shorter visits.",
    address: "11 W Gay St, Columbus, OH 43215",
    phone: "614-745-3864",
    email: "info@veritasrestaurant.com",
    website: "https://veritasrestaurant.com/",
    menuUrl: "https://veritasrestaurant.com/menus-1",
    menu: ["Seasonal tasting", "Bar menu", "Wine pairing"],
    menuSections: [
      { title: "Tasting menu", items: ["Rotating themed courses", "Vegetarian-friendly accommodations", "Optional beverage pairing"] },
      { title: "Bar menu", items: ["Champagne and cocktails", "Caviar snacks", "Lobster roll and croquettes"] },
      { title: "Dessert finish", items: ["Plated final course", "Soft-serve style sweets", "After-dinner pours"] },
    ],
    status: "open",
    statusLabel: "Open",
    position: "0% 0%",
  },
  {
    name: "The Refectory",
    cuisine: "French and European",
    area: "Bethel Road",
    rating: "4.8",
    reviews: "2.1k",
    price: "$15-$115",
    priceTier: "$$$$",
    hours: "Wed-Thu, 5:15-8:30 pm; Fri-Sat, 4:45-9 pm",
    description: "A Columbus institution for polished French cooking, an exceptional cellar, and unhurried evenings.",
    about:
      "The Refectory is a candlelit Columbus landmark that layers classic French technique, formal service, and one of the city's deepest wine programs into a true destination dinner.",
    address: "1092 Bethel Rd, Columbus, OH 43220",
    phone: "614-451-9774",
    website: "https://refectory.com/",
    menuUrl: "https://refectory.com/dinner-menu/",
    menu: ["A la carte dinner", "Chef tasting", "Wine cellar"],
    menuSections: [
      { title: "Prelude and starters", items: ["Daily soups", "Seasonal salads", "Charcuterie and seafood starters"] },
      { title: "Main courses", items: ["Seafood course", "Meat course", "Cheese course and bread service"] },
      { title: "Signature extras", items: ["Four-course tasting", "Five-course vegetarian tasting", "Wine and spirits pairings"] },
    ],
    status: "open",
    statusLabel: "Open",
    position: "50% 0%",
  },
  {
    name: "Chapman's Eat Market",
    cuisine: "New American",
    area: "German Village",
    rating: "4.7",
    reviews: "1.7k",
    price: "$16-$48",
    priceTier: "$$$",
    hours: "Closed",
    description: "Inventive shared plates and cult-favorite desserts in a lively, design-forward dining room.",
    about:
      "Chapman's helped define modern neighborhood dining in Columbus with playful, tightly edited plates and a packed, high-energy room in German Village.",
    address: "739 S 3rd St, Columbus, OH 43206",
    website: "https://www.eatchapmans.com/",
    menu: ["Shared plates", "Pasta", "Dessert"],
    menuSections: [{ title: "Former style of service", items: ["Shareable starters", "Creative mains", "Desserts that changed often"] }],
    status: "closed",
    statusLabel: "Closed",
    statusNote: "Chapman's official site says the restaurant has closed and now points guests to private events plus sister concepts in Columbus.",
    position: "100% 0%",
  },
  {
    name: "Agni",
    cuisine: "Modern Indian",
    area: "Brewery District",
    rating: "4.8",
    reviews: "820",
    price: "$22-$95",
    priceTier: "$$$",
    hours: "Wed-Sun, 5-10:30 pm",
    description: "A striking modern Indian menu with a sense of place, heat, smoke, and carefully layered spice.",
    about:
      "Agni blends tasting-menu precision with Indian flavors, live-fire energy, and a sleek room that feels built for a long, multi-course night out.",
    address: "716 S High St, Columbus, OH 43206",
    phone: "614-674-6600",
    email: "reservations@dineatagni.com",
    website: "https://www.dineatagni.com/",
    menuUrl: "https://www.dineatagni.com/menu",
    menu: ["Tasting menu", "Vegetarian menu", "Cocktails"],
    menuSections: [
      { title: "Chef-led formats", items: ["Signature tasting menu", "Vegetarian tasting", "Bar seating experiences"] },
      { title: "Flavor profile", items: ["Smoke and spice", "Indian technique through a modern lens", "Seasonal Ohio ingredients"] },
      { title: "Drinks", items: ["Cocktail pairings", "Wine pairings", "Zero-proof options"] },
    ],
    status: "open",
    statusLabel: "Open",
    position: "0% 50%",
  },
  {
    name: "Lindey's",
    cuisine: "American and patio dining",
    area: "German Village",
    rating: "4.6",
    reviews: "5.8k",
    price: "$15-$35",
    priceTier: "$$$",
    hours: "Sun-Thu, 11 am-10 pm; Fri-Sat, 11 am-11 pm",
    description: "Reliable hospitality, polished American plates, and one of the city's loveliest courtyard patios.",
    about:
      "Lindey's is one of Columbus' classic all-around restaurants, known for polished service, a handsome dining room, and a patio that keeps locals coming back year after year.",
    address: "169 E Beck St, Columbus, OH 43206",
    phone: "614-228-4343",
    website: "https://www.lindeys.com/",
    menuUrl: "https://www.lindeys.com/menus",
    menu: ["Brunch", "Dinner", "Dessert"],
    menuSections: [
      { title: "Meal periods", items: ["Weekend brunch", "Weekday lunch", "Nightly dinner"] },
      { title: "Core categories", items: ["Appetizers", "Soups and salads", "Entrees and sandwiches"] },
      { title: "Extra menus", items: ["Dessert menu", "Wine list", "Happy hour"] },
    ],
    status: "open",
    statusLabel: "Open",
    position: "50% 50%",
  },
  {
    name: "Akai Hana",
    cuisine: "Japanese and sushi",
    area: "Northwest",
    rating: "4.6",
    reviews: "3.5k",
    price: "$5-$23",
    priceTier: "$$",
    hours: "Mon-Thu, 5-9 pm; Fri-Sat, 4-9 pm; Sun, 4-8 pm",
    description: "A long-running destination for pristine sashimi, comforting noodle bowls, and deep sushi-menu variety.",
    about:
      "Akai Hana remains one of Columbus' most complete Japanese menus, spanning sushi, sashimi, noodle bowls, boxed meals, and specialty rolls without losing the feel of a neighborhood institution.",
    address: "1173 Old Henderson Rd, Columbus, OH 43220",
    phone: "614-451-5411",
    website: "https://akaihana.japanmarketplace.com/",
    menuUrl: "https://akaihana.japanmarketplace.com/menu",
    menu: ["Sushi and sashimi", "Noodles and bowls", "Special rolls"],
    menuSections: [
      { title: "Sushi bar", items: ["Nigiri and sashimi", "Regular rolls", "Special rolls and party boats"] },
      { title: "Kitchen menu", items: ["Entrees", "Box meals", "Noodles and rice bowls"] },
      { title: "Extras", items: ["Appetizers", "Kids menu", "Desserts, sake, and beer"] },
    ],
    status: "open",
    statusLabel: "Open",
    position: "100% 50%",
  },
  {
    name: "Los Guachos",
    cuisine: "Mexican and tacos",
    area: "Northwest",
    rating: "4.7",
    reviews: "6.4k",
    price: "$4-$16",
    priceTier: "$",
    hours: "Sun-Thu, 11 am-midnight; Fri-Sat, 11 am-1 am",
    description: "The go-to for al pastor cut to order, quick plates, and a late-night Columbus ritual.",
    about:
      "Los Guachos built its name on proper al pastor and fast, generous plates, and the Godown Road location still feels like a Columbus essential when the taco craving hits.",
    address: "5221 Godown Rd, Columbus, OH 43235",
    phone: "614-538-0211",
    email: "nonatoe@yahoo.com",
    website: "https://losguachostaqueria.com/",
    menuUrl: "https://losguachostaqueria.com/columbus-los-guachos-taqueria-godown-rd-food-menu",
    menu: ["Tacos al pastor", "Tortas", "Burritos"],
    menuSections: [
      { title: "Street-style staples", items: ["Gringas", "Tacos", "Volcanes and huaraches"] },
      { title: "Bigger plates", items: ["Quesadillas", "Tortas", "Burritos"] },
      { title: "Sides and extras", items: ["Soups and salads", "Chips and dips", "Kids menu and sides"] },
    ],
    status: "open",
    statusLabel: "Open",
    position: "0% 100%",
  },
  {
    name: "Momo Ghar",
    cuisine: "Nepalese and Tibetan",
    area: "Downtown",
    rating: "4.7",
    reviews: "2.3k",
    price: "$12-$19",
    priceTier: "$",
    hours: "Mon, 10 am-5 pm; Tue-Sat, 10 am-7 pm; Sun, 10 am-5 pm",
    description: "Hand-folded dumplings and vibrant Himalayan comfort food with a devoted local following.",
    about:
      "Momo Ghar centers its appeal on handmade momos and deeply comforting Himalayan flavors, with a compact downtown footprint that keeps the focus on the food.",
    address: "59 Spruce St, Columbus, OH 43215",
    phone: "614-495-6666",
    website: "https://momoghar.com/",
    menu: ["Momos", "Noodle soups", "Chili dishes"],
    menuSections: [
      { title: "Signature dumplings", items: ["Steamed momos", "Pan-fried momos", "Sauce-driven momo plates"] },
      { title: "Comfort dishes", items: ["Thukpa-style soups", "Rice plates", "Spicy stir-fried favorites"] },
      { title: "Best way to order", items: ["Mix dumplings and soup", "Add spice carefully", "Check the board for daily specials"] },
    ],
    status: "open",
    statusLabel: "Open",
    position: "50% 100%",
  },
  {
    name: "Hiraeth",
    cuisine: "Seasonal tasting",
    area: "Short North",
    rating: "4.8",
    reviews: "460",
    price: "$24-$120",
    priceTier: "$$$$",
    hours: "Verify before planning",
    description: "An intimate tasting-menu counter with thoughtful service and ingredient-led courses.",
    about:
      "Hiraeth arrived as a moody, live-fire dining room built around seasonal sharing plates and a memorable downstairs dining experience.",
    address: "36 E Lincoln St, Columbus, OH 43215",
    phone: "614-824-4516",
    menu: ["Shared plates", "Seasonal mains", "Cocktails and wine"],
    menuSections: [{ title: "Previously known for", items: ["Seasonal shared plates", "Live-fire mains", "Cocktail and wine pairings"] }],
    status: "limited",
    statusLabel: "Events or limited service",
    statusNote:
      "Recent local coverage reported regular dinner service ended and the space shifted toward events and private bookings, so treat this listing as a historical favorite and confirm availability before planning a visit.",
    position: "100% 100%",
  },
  {
    name: "Basi Italia",
    cuisine: "Italian",
    area: "Victorian Village",
    rating: "4.7",
    reviews: "1.9k",
    price: "$12-$34",
    priceTier: "$$$",
    hours: "Tue-Thu, 5-9 pm; Fri-Sat, 5-10 pm",
    description: "Cozy, romantic Italian cooking with house-made pasta and a neighborhood feel.",
    about:
      "Basi Italia leans intimate and relaxed, with a tucked-away dining room, a beloved patio, and a seasonal Italian menu that feels polished without becoming fussy.",
    address: "811 Highland St, Columbus, OH 43215",
    phone: "614-294-7383",
    email: "trishandjohn@basi-italia.com",
    website: "https://www.basi-italia.com/",
    menu: ["Seasonal pasta", "Antipasti", "Wine"],
    menuSections: [
      { title: "Italian foundations", items: ["Antipasti", "Seasonal pasta", "Mediterranean-inspired entrees"] },
      { title: "Dinner style", items: ["Small cozy dining room", "Patio and veranda wine energy", "Seasonal produce focus"] },
      { title: "Useful notes", items: ["Reservations encouraged", "Carryout available", "Wine-driven evening spot"] },
    ],
    status: "open",
    statusLabel: "Open",
    position: "50% 0%",
  },
  {
    name: "Wario's Beef & Pork",
    cuisine: "Sandwiches",
    area: "Downtown",
    rating: "4.8",
    reviews: "2.2k",
    price: "$7-$20",
    priceTier: "$$",
    hours: "Wed, 11 am-7 pm; Thu-Sat, 11 am-midnight; Sun, 11 am-9 pm",
    description: "Big, messy, meticulously built sandwiches that have become a destination in their own right.",
    about:
      "Wario's does chef-driven sandwich-shop food with very little compromise, turning a short menu of East Coast-inspired subs into one of downtown's most dependable cravings.",
    address: "111 W Nationwide Blvd, Columbus, OH 43215",
    phone: "614-914-8338",
    website: "https://www.wariosbeefandpork614.com/",
    menuUrl: "https://www.wariosbeefandpork614.com/menu-downtown",
    menu: ["Cheesesteak", "Roasted pork", "Spuds"],
    menuSections: [
      { title: "Sandwiches", items: ["The Steak", "Roasted Pork", "Cold Cut and chicken sandwiches"] },
      { title: "Sides", items: ["House spuds", "Wario spuds", "Caesar and pasta salad"] },
      { title: "Add-ons", items: ["Long hots", "House whiz", "Wario sauce and giardiniera"] },
    ],
    status: "open",
    statusLabel: "Open",
    position: "100% 50%",
  },
  {
    name: "Comune",
    cuisine: "Plant-based",
    area: "Schumacher Place",
    rating: "4.7",
    reviews: "1.1k",
    price: "$7-$32",
    priceTier: "$$",
    hours: "Mon-Thu, 5-9 pm; Fri-Sat, 5-10 pm",
    description: "A polished plant-forward restaurant where vegetables get the center-of-the-plate treatment.",
    about:
      "Comune is one of Columbus' standout modern dining rooms, proving plant-forward food can feel generous, creative, and fully night-out worthy rather than simply virtuous.",
    address: "677 Parsons Ave, Columbus, OH 43206",
    phone: "614-947-1012",
    email: "info@comune-restaurant.com",
    website: "https://www.comune-restaurant.com/",
    menuUrl: "https://www.comune-restaurant.com/",
    menu: ["Shareable vegetables", "Natural wine", "Seasonal desserts"],
    menuSections: [
      { title: "Menu rhythm", items: ["Sharable small plates", "Vegetable-focused mains", "Dessert to finish"] },
      { title: "Drinks", items: ["Craft cocktails", "Natural and biodynamic wine", "Thoughtful non-alcoholic options"] },
      { title: "Best known for", items: ["Seasonal produce", "Globally inspired flavors", "A very polished vegan-friendly night out"] },
    ],
    status: "open",
    statusLabel: "Open",
    position: "0% 0%",
  },
  {
    name: "Joya's Cafe",
    cuisine: "Indian-inspired cafe",
    area: "Worthington",
    rating: "4.7",
    reviews: "1.5k",
    price: "$13-$19",
    priceTier: "$$",
    hours: "Tue-Thu, 8 am-2 pm; Fri-Sat, 8 am-6 pm; Sun, 8 am-2 pm",
    description: "Bright, craveable daytime cooking that moves freely between Indian flavors and Midwest comfort.",
    about:
      "Joya's has one of the most distinctive daytime menus around Columbus, mixing Bengali-American flavor ideas, cafe comfort, and a short list of dishes people happily line up for.",
    address: "657 High St, Worthington, OH 43085",
    phone: "614-468-1232",
    email: "hello@eatatjoyas.com",
    website: "https://www.eatatjoyas.com/",
    menuUrl: "https://www.eatatjoyas.com/menu",
    menu: ["Breakfast sandwiches", "Fried rice", "Milk chai"],
    menuSections: [
      { title: "Daytime mains", items: ["Breakfast sandwiches", "Kati roll and tacos", "Not Pad Thai and fried rice"] },
      { title: "Vegetarian-friendly picks", items: ["Vegetarian breakfast sandwich", "Potato-and-black-bean taco option", "Tofu Manchurian sandwich"] },
      { title: "Drinks and treats", items: ["Milk chai", "Coffee drinks", "Rotating pastry and sweet options"] },
    ],
    status: "open",
    statusLabel: "Open",
    position: "0% 50%",
  },
  {
    name: "The Guild House",
    cuisine: "New American",
    area: "Short North",
    rating: "4.5",
    reviews: "3.7k",
    price: "$7-$59",
    priceTier: "$$$",
    hours: "Mon-Fri, 7 am-10 pm; Sat, 9 am-10 pm; Sun, 9 am-9 pm",
    description: "A handsome Short North mainstay built around seasonal produce, craft cocktails, and social dinner energy.",
    about:
      "The Guild House works well as both a polished dinner reservation and a flexible all-day option, thanks to a broad menu, central Short North address, and steady Cameron Mitchell service standards.",
    address: "624 N High St, Columbus, OH 43215",
    phone: "614-280-9780",
    website: "https://theguildhousecolumbus.com/",
    menuUrl: "https://theguildhousecolumbus.com/menus/",
    menu: ["Breakfast and brunch", "Dinner", "Happy hour"],
    menuSections: [
      { title: "Meal periods", items: ["Breakfast", "Lunch or brunch", "Dinner"] },
      { title: "Dinner categories", items: ["Raw bar", "Market vegetables and starters", "Seasonal mains and steaks"] },
      { title: "Extra menus", items: ["Dessert", "Beverage menu", "Happy hour and kids menu"] },
    ],
    status: "open",
    statusLabel: "Open",
    position: "50% 50%",
  },
  {
    name: "Min-Ga Korean Restaurant",
    cuisine: "Korean",
    area: "Bethel Road",
    rating: "4.6",
    reviews: "2.5k",
    price: "$5-$30",
    priceTier: "$$",
    hours: "Mon-Thu, 11:30 am-9 pm; Fri-Sun, 11:30 am-9:30 pm",
    description: "Soulful Korean cooking with bubbling stews, barbecue, and generous shareable plates.",
    about:
      "Min-Ga is the kind of Korean restaurant locals return to for dependable classics, a broad menu, and the comfort of hot stone bowls, soups, barbecue, and side dishes in one place.",
    address: "800 Bethel Rd, Columbus, OH 43214",
    phone: "614-457-7331",
    email: "mingakoreanrestaurant@gmail.com",
    website: "https://www.min-gakoreanrestaurant.com/",
    menuUrl: "https://www.min-gakoreanrestaurant.com/menu",
    menu: ["Korean BBQ", "Bibimbap", "Stews"],
    menuSections: [
      { title: "Core Korean staples", items: ["Bibimbap", "Soups and stews", "Korean barbecue plates"] },
      { title: "More to explore", items: ["Noodle dishes", "Hot plates", "Shareable appetizers"] },
      { title: "Dining style", items: ["Dine-in and carryout", "Family-style comfort", "Great for groups who want variety"] },
    ],
    status: "open",
    statusLabel: "Open",
    position: "100% 100%",
  },
  {
    name: "Katalina's",
    cuisine: "Brunch and Latin-leaning cafe",
    area: "Harrison West",
    rating: "4.6",
    reviews: "4.9k",
    price: "$5-$18",
    priceTier: "$$",
    hours: "Daily, 8 am-3 pm",
    description: "A beloved, cheerful brunch stop known for pancake balls, migas, and a lively little dining room.",
    about:
      "Katalina's is one of Columbus' classic daytime stops, mixing big flavors, fast-moving brunch energy, and a menu that still feels local after years of popularity.",
    address: "1105 Pennsylvania Ave, Columbus, OH 43201",
    website: "https://www.katalinas.com/",
    menu: ["Pancake balls", "Breakfast plates", "Coffee"],
    menuSections: [
      { title: "Morning favorites", items: ["Original Pancake Balls", "Migas and breakfast plates", "Breakfast tacos and sandwiches"] },
      { title: "Lunch-friendly picks", items: ["Bowls and plates", "Taco kits and takeout", "Seasonal specials"] },
      { title: "Useful notes", items: ["Pickup and delivery", "No reservations", "Great for casual brunch planning"] },
    ],
    status: "open",
    statusLabel: "Open",
    position: "50% 0%",
  },
  {
    name: "Rooh Columbus",
    cuisine: "Progressive Indian",
    area: "Short North",
    rating: "4.5",
    reviews: "1.3k",
    price: "$7-$41",
    priceTier: "$$$",
    hours: "Mon-Thu, 5-9 pm; Fri, 9 am-1 pm and 5-10 pm; Sat, 8:30 am-1:30 pm and 5-10 pm; Sun, 8:30 am-1:30 pm",
    description: "Refined regional Indian flavors rendered through modern technique and stylish cocktails.",
    about:
      "Rooh turns Indian regional flavors into a more polished night out, with an especially strong cocktail program and a Short North dining room that works for both dinner and weekend brunch.",
    address: "685 N High St, Columbus, OH 43215",
    phone: "614-972-8678",
    email: "info@roohcolumbus.com",
    website: "https://www.roohcolumbus.com/",
    menuUrl: "https://www.roohcolumbus.com/eat",
    menu: ["Small plates", "Curries", "Cocktails"],
    menuSections: [
      { title: "Dinner", items: ["Snackable starters", "Regional mains and curries", "Plated desserts"] },
      { title: "Brunch and cafe", items: ["Weekend brunch", "Savory breakfast plates", "Pastries and coffee drinks"] },
      { title: "Bar program", items: ["Signature cocktails", "Happy hour drinks", "Beer, spirits, and zero-proof options"] },
    ],
    status: "open",
    statusLabel: "Open",
    position: "100% 0%",
  },
  {
    name: "Si Senor",
    cuisine: "Peruvian sandwiches",
    area: "Grandview",
    rating: "4.6",
    reviews: "1.8k",
    price: "$3-$14",
    priceTier: "$$",
    hours: "Mon-Fri, 11 am-3 pm and 5-8:30 pm; Sat, noon-4 pm",
    description: "A warm, family-run favorite for generous Peruvian sandwiches, bright sauces, and easygoing lunches.",
    about:
      "Si Senor has carved out a lane of its own in Columbus with Peruvian sandwiches, scratch-made sauces, and quick-service warmth that makes it especially strong for lunch.",
    address: "1456 W 5th Ave, Columbus, OH 43212",
    phone: "614-670-4985",
    email: "sisenorcolumbus@gmail.com",
    website: "https://www.sisenor-columbus.com/",
    menuUrl: "https://sisenor-columbus.com/columbus-si-senor-peruvian-sandwiches-food-menu",
    menu: ["Peruvian sandwiches", "Salads", "Desserts"],
    menuSections: [
      { title: "Sandwiches", items: ["Chicharron", "Jumping Beef", "Chipotle Chicken and turkey options"] },
      { title: "Sides and salads", items: ["Avocado and Peruvian salads", "Plantains and soup", "Combo add-ons"] },
      { title: "Dessert and drinks", items: ["Tres leches cake", "House-made extras", "Inca Kola and bottled drinks"] },
    ],
    status: "open",
    statusLabel: "Open",
    position: "0% 100%",
  },
  {
    name: "Harvest Bar + Kitchen",
    cuisine: "Farm-driven pizza and American plates",
    area: "Clintonville",
    rating: "4.5",
    reviews: "2.8k",
    price: "$12-$19",
    priceTier: "$$$",
    hours: "Tue-Sun, 11 am-10 pm",
    description: "Seasonal Ohio produce, wood-fired pizza, and a cozy neighborhood room with a polished bar program.",
    about:
      "Harvest's Clintonville location balances neighborhood comfort with a more considered food-and-drink program, built around farm-driven pizzas, small plates, salads, and cocktails.",
    address: "2885 N High St, Columbus, OH 43202",
    phone: "614-947-7133",
    website: "https://www.harvestpizzeria.com/harvest/locations/clintonville",
    menu: ["Wood-fired pizza", "Small plates", "Cocktails"],
    menuSections: [
      { title: "House specialties", items: ["Wood-fired pizzas", "Burgers and sandwiches", "Seasonal salads"] },
      { title: "Shareables", items: ["Buffalo cauliflower", "Brussels sprouts", "Snackable starters"] },
      { title: "Good to know", items: ["Happy hour on weekdays", "Two patio areas", "Strong cocktail focus"] },
    ],
    status: "open",
    statusLabel: "Open",
    position: "100% 50%",
  },
  {
    name: "Yoshi",
    cuisine: "Japanese and sushi",
    area: "Dublin",
    rating: "4.7",
    reviews: "940",
    price: "$18-$180",
    priceTier: "$$$",
    hours: "Mon-Sat, 5-9 pm",
    description: "A tiny, chef-led sushi destination where the counter experience is the main event.",
    about:
      "Yoshi works as both a traditional Japanese restaurant and a sushi destination, with private dining options, chef's special omakase, and a menu broad enough for mixed groups.",
    address: "5776 Frantz Rd, Dublin, OH 43016",
    phone: "614-889-1275",
    email: "yoshisjapanese@gmail.com",
    website: "https://www.yoshisjapanese.com/",
    menu: ["Sushi menu", "Dinner menu", "Beverage menu"],
    menuSections: [
      { title: "Sushi bar", items: ["Sashimi and nigiri", "Specialty rolls", "Chef's omakase options"] },
      { title: "Kitchen dishes", items: ["Traditional Japanese entrees", "Appetizers", "Noodle dishes"] },
      { title: "Planning notes", items: ["Private dining rooms", "Dinner service only", "Reservations by phone"] },
    ],
    status: "open",
    statusLabel: "Open",
    position: "50% 100%",
  },
];

export const restaurantSlug = (name: string) =>
  name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

export const restaurantDetails = entries.map((restaurant) => ({
  ...restaurant,
  slug: restaurantSlug(restaurant.name),
}));
